// File generated by FlutterFire CLI - CONFIGURED for TRENDIFY
// Firebase Project: trendify-fashion-store
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtPE4moPZDE8F517tCQNpn6WfrvpS4rps',
    appId: '1:637872312098:web:3d5a1a7851e41314d91f7b',
    messagingSenderId: '637872312098',
    projectId: 'trendify-fashion-store',
    authDomain: 'trendify-fashion-store.firebaseapp.com',
    storageBucket: 'trendify-fashion-store.firebasestorage.app',
    measurementId: 'G-R8CCEZVT1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtPE4moPZDE8F517tCQNpn6WfrvpS4rps',
    appId: '1:637872312098:android:3d5a1a7851e41314d91f7b',
    messagingSenderId: '637872312098',
    projectId: 'trendify-fashion-store',
    storageBucket: 'trendify-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtPE4moPZDE8F517tCQNpn6WfrvpS4rps',
    appId: '1:637872312098:ios:3d5a1a7851e41314d91f7b',
    messagingSenderId: '637872312098',
    projectId: 'trendify-fashion-store',
    storageBucket: 'trendify-fashion-store.firebasestorage.app',
    iosBundleId: 'com.trendify.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtPE4moPZDE8F517tCQNpn6WfrvpS4rps',
    appId: '1:637872312098:ios:3d5a1a7851e41314d91f7b',
    messagingSenderId: '637872312098',
    projectId: 'trendify-fashion-store',
    storageBucket: 'trendify-fashion-store.firebasestorage.app',
    iosBundleId: 'com.trendify.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtPE4moPZDE8F517tCQNpn6WfrvpS4rps',
    appId: '1:637872312098:web:3d5a1a7851e41314d91f7b',
    messagingSenderId: '637872312098',
    projectId: 'trendify-fashion-store',
    authDomain: 'trendify-fashion-store.firebaseapp.com',
    storageBucket: 'trendify-fashion-store.firebasestorage.app',
    measurementId: 'G-R8CCEZVT1M',
  );
}
